### ISSUE TITLE
No realiza la compra

### ISSUE THREAD

**Issue by GuabinaCore** [joanroig/pccomponentes-outlet-bot#1]
Al cambiar la URL de busqueda por una como por ejemplo https://www.pccomponentes.com/listado/ajax?idFamilies[]=6&order=price-desc

El sistema reconoce las tarjetas, inclusive se loguea bien y realiza la notificacion via telegram.  Pero no realiza ni el intento de compra.

![image](https://user-images.githubusercontent.com/42710853/105482290-7610b680-5ca8-11eb-8710-55875589f4ac.png)

Saludos!

**Comment by joanroig** [comment]
Hola, el sistema de compra lo puse en una branch a parte porque no está muy pulido, la configuración extra necesaria está explicada en el README y tienes que modificar el objeto "purchaseCombos" de la configuración con el precio mínimo de compra y las keywords de cada modelo que busques.
https://github.com/joanroig/pccomponentes-outlet-bot/tree/purchase-system
Ten en cuenta que el sistema intentará comprar todos los productos que hagan matching, no implementé un límite (no debería ser muy complicado).
Saludos

**Comment by GuabinaCore** [comment]
Hola gracias por tu respuesta, si estoy usando el branch de autocompra y estoy haciendo la configuracion extra necesaria, como podras notar en la imagen se ve que el bot hace el logueo en la pagina web correctamente y detecta los productos que hacen matching, hasta realiza la alerta via telegram, pero no realiza ninguna compra, no se si quizas pccomponentes haya actualizado algo y dejo de funcionar. Saludos!

**Comment by joanroig** [comment]
@GuabinaCore He actualizado la branch para solucionar el bug que comentabas y de paso he terminado la implementación del sistema de compra.
Una vez inicie el proceso de compra, no se ejecutará más de una vez hasta terminar. En caso que una compra sea satisfactoria el bot terminará la ejecución.
Espero que sirva :)

**Comment by GuabinaCore** [comment]
@joanroig Ahora si casi realiza el proceso de compra completo, lo mete en el carrito, llegas al paso que es confirmar los datos (tarjeta de credito, direccion de envio, etc) pero para seguir al siguiente paso final que es haciendo el check en la casilla "entiendo las condiciones" para luego darle click en "Pagar y Finalizar" crashea tirando el siguiente error 

![image](https://user-images.githubusercontent.com/42710853/105535123-bbf06d80-5cee-11eb-9a3c-efce744cc77c.png)

**Comment by joanroig** [comment]
Prueba a actualizar la branch, hacer npm install y a ver si esta vez funciona.
De lo contrario inspecciona el botón de transferencia ordinaria y súbeme código o pantallazo para ver si tiene el "tipopago5" en la clase HTML:
<img width="968" alt="Screenshot 2021-01-22 at 20 58 01" src="https://user-images.githubusercontent.com/12451419/105539056-92d2db80-5cf4-11eb-85a3-da4a5a0ebaca.png">

**Comment by GuabinaCore** [comment]
Hola @joanroig hice lo que me pediste, ahora cambió el error y pasa algo curioso, cuando el bot realiza la compra no aparece la opcion de pagar por transferencia como podras verlo en estos 2 pantallazos

![image](https://user-images.githubusercontent.com/42710853/105543514-28249e80-5cfa-11eb-82e6-bd0376925150.png)
![image](https://user-images.githubusercontent.com/42710853/105544274-1394d600-5cfb-11eb-929b-f70bc74a5f8d.png)

Pero luego si hago la compra normal sin el bot fijate como si aparece la opcion
![image](https://user-images.githubusercontent.com/42710853/105544675-843bf280-5cfb-11eb-92d9-38bff7135f89.png)

**Comment by joanroig** [comment]
Creo que pasa porque en mi caso las pruebas las hago con una cuenta nueva sin tarjeta vinculada, si puedes probarlo con una cuenta nueva o desvinculando la tarjeta probablemente se solucione el problema. Supongo que al tenerla vinculada el identificador cambia. 
Parte del código que uso originalmente estaba pensado para hacer compras con tarjeta, puedes reutilizar parte del código del proyecto original:
https://github.com/elpatronaco/pccomponentes-buy-bot

**Comment by Sofian060** [comment]
HOLA BUENAS, QUERÍA COMENTAR QUE ME DA UNA SERIE DE FALLOS ??

DevTools listening on ws://127.0.0.1:56102/devtools/browser/ac67b38b-974d-4cc2-992f-1
**ERROR NOT CAUGHT WHILE RUNNING BOT. MORE INFO BELOW
SessionNotCreatedError: session not created: This version of ChromeDriver only suppor
Current browser version is 89.0.4389.114 with binary path C:\Program Files (x86)\Goog
    at Object.throwDecodedError (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-ou
    at parseHttpResponse (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bo
    at Executor.execute (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {**

Y EL SIGUIENTE FALLO ES A LA HORA DE HACER LA COMPRA !!
 
ERROR NOT CAUGHT WHILE RUNNING BOT. MORE INFO BELOW
TypeError: Cannot read property 'navigate' of undefined
    at Purchase.<anonymous> (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet
    at step (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot-purchase-sy
    at Object.next (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot-purc
    at C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot-purchase-system\p
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot-purcha
    at Purchase.runItem (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot
    at Purchase.<anonymous> (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet
    at step (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot-purchase-sy
    at Object.next (C:\Users\HP.DESKTOP-0RRVQT0\Desktop\pccomponentes-outlet-bot-purc
Purchase failed...

Habría Alguna Manera de Solucionar esto ???
Graciasss!!1
