### ISSUE TITLE
Python?

### ISSUE THREAD

**Issue by diogoribeirodev** [joanroig/pccomponentes-outlet-bot#30]
**Is your feature request already submitted? Please check the [enhancements](https://github.com/joanroig/pccomponentes-bot/labels/enhancement) and the [tasks](https://github.com/joanroig/pccomponentes-bot/projects/1).**
Please do not open new issues if the feature has already been submitted or considered in the tasks.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hey, i was wondering you have a python version for this? Also what about implement options on tg where we would send a command to the bot and he would do the actions according to the command. Example, he sends a message saying rtx 3060 available for 350€, you want to buy? , he would have a button afterthe message saying Buy, we would click it and he would buy.
**Describe alternatives you've considered**

**Additional context**

**Comment by joanroig** [comment]
Hello, sorry but there are no plans about migrating to Python.
